<a href="https://colab.research.google.com/github/Chan0226/Deep-Learning/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D(%EA%B9%8A%EC%9D%80_%EB%8B%A4%EC%B8%B5%ED%8D%BC%EC%85%89%ED%8A%B8%EB%A1%A0).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 텐서플로우, 파이토치

In [ ]:
import tensorflow as tf
print(tf.__version__) 


2.7.0


In [ ]:
a = tf.random_uniform_initializer()
print(a)
print(type(a))

<class 'tensorflow.python.ops.init_ops_v2.RandomUniform'>


In [ ]:
# 다차원 배열 텐서
# 데이터를 텐서
# 신경망의 가중치(매개변수)를 텐서로 표현 -- > 다차원 배열
# 넘파이는 ndarray클래스    텐서플로우는 Tensor 클래스

In [ ]:
# 데이터 읽어오기
import tensorflow as tf
import tensorflow.keras.datasets as ds

In [ ]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
mnist = fetch_openml('mnist_784')
x_train,x_test,y_train,y_test =  train_test_split(mnist.data, mnist.target)

In [ ]:
# 특징.... 사이킷런...... 데이터 load xxxx 가져오고
# train.... split   테이터를 학습용과 훈련용으로
# x_train,x_test,y_train,y_test = 
#케라스는 데이터를 가져오면서 동시에 학습용과 훈련용으로 나눔
(x_train,y_train),(x_test,y_test) = ds.mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
(x_train,y_train),(x_test,y_test) = ds.mnist.load_data()
print(x_train.shape, y_train.shape)

(60000, 28, 28) (60000,)


In [ ]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
# 텐서플로 XOR 문제 
import tensorflow as tf


In [ ]:
# data
x = [[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]]
y = [[-1],[1],[1],[1]]


In [ ]:
# 가중치를 설정
w = tf.Variable([[1.0],[1.0]])
b = tf.Variable(-0.5)

In [ ]:
# 다층 퍼셉트론 동작
s = tf.add(tf.matmul(x,w),b)
o = tf.sign(s)
o

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-1.],
       [ 1.],
       [ 1.],
       [ 1.]], dtype=float32)>